### ISSUE TITLE
Demo failing on Vercel - Runtime.UnhandledPromiseRejection

### ISSUE THREAD

**Issue by mirkokiefer** [second-state/vercel-wasm-runtime#2]
Would love to get this working - hitting this error on Vercel:

```
[GET] /api/hello
20:36:29:56
2021-09-11T13:36:30.095Z	be9096ad-e534-4368-943b-9c6fee2dd916	ERROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received undefined","reason":{"errorType":"TypeError","errorMessage":"The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received undefined","code":"ERR_INVALID_ARG_TYPE","stack":["TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received undefined","    at Socket.Writable.write (internal/streams/writable.js:285:13)","    at module.exports (/var/task/api/hello.js:20:18)","    at Server.<anonymous> (/var/task/___vc/__helpers.js:813:19)","    at Server.emit (events.js:400:28)","    at parserOnIncoming (_http_server.js:897:12)","    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: TypeError [ERR_INVALID_ARG_TYPE]: The \"chunk\" argument must be of type string or an instance of Buffer or Uint8Array. Received undefined","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:412:35)","    at processPromiseRejections (internal/process/promises.js:245:33)","    at processTicksAndRejections (internal/process/task_queues.js:96:32)"]}
Unknown application error occurred

```

![](https://cdn.zappy.app/d252d689883a8b1ab1281f4b7a2e7174.png)

**Comment by juntao** [comment]
For the /api/hello endpoint, you need to do a http POST with an image as the POST body. 

This error shows that you are trying to do a http GET ...

**Comment by mirkokiefer** [comment]
Thanks yes, turns out the real error was a `FUNCTION_PAYLOAD_TOO_LARGE` and didn't show up in the Vercel logs.. Trying with an image less than 5mb worked!

https://vercel.com/docs/limits/overview#serverless-function-payload-size-limit
